### ISSUE TITLE
Modernize hpcs module - only standard plan + add hybrid support

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-hpcs#11]
### Description

- HPCS instance:
   - We're going to repurpose the existing legacy repository at https://github.com/terraform-ibm-modules/terraform-ibm-hpcs . This module has not been updated for over 3 years, so we'll have a new major version. Do not worry about backward compatibility,etc (there is no public release yet) - we could replace the entire code in that repo if this is the easiest path (rather than migrating).
   - There are 2 different ways to create a HPCS instance:
      - Using the resource controller terraform (like here: https://github.com/terraform-ibm-modules/terraform-ibm-hpcs/blob/4eb8c2ba2700cfc53a6cd810af9b5ef9020f1197/modules/ibm-hpcs-instance/main.tf#L6 )
      - Using the hpcs resource at https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/hpcs
         - The hpcs resource create an instance AND initializes it using the recovery crypto unit. This approach is only available in us-source / us-east.
      - So, the current thinking is to have the module either either one or the other method depending on the type of initialization.  
      - There will be manual steps needed (that needs to be documented - simply pointing to IBM Cloud doc is sufficient for tose step) to (1) create the admin secrets using the CLI (2) initialize the HPCS instance in the case where customer wants to initialize with multi part files, or smart card (there is no terraform support for those)
      - Additional context - there is also an hybrid HPCS story coming in parallel that is only available through additional parameters in the resource  ibm_resource_instance terraform block (more details to follow)
- As part of this effort, suggest to start from the template https://github.com/terraform-ibm-modules/terraform-ibm-module-template
- Creating key and key rings
   - Objective is to reuse the same set of modules for key protect and hpcs. These should in theory work, but this needs to be validated. ( https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-key-ring and https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-key )
   - If this is validated:
      - Update the 2 modules https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-key-ring and https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-key to (1) use the term kms instead of key protect (2) mention compatibility 
      -  Add examples + corresponding terratest that create key rings / key against an HPCS instance, so that we can ensure there is no regression
 

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
@Aashiq-J @maheshwarishikha - On the hybrid HPCS story, this is a small additional on top of the support based on ibm_resource_instance:
- Take 1 new input parameter named hsm_connector_id (string) - default to null. Indicate that this is only available to selected consumers. The ID is provided by IBM.
- When this input parameter is set the 3 "parameters" value in ibm_resource_instance to:
   units: "3", # this is fixed value for Hybrid-HPCS
   byohsm: "true", # this is fixed value for Hybrid-HPCS
   hsm_connector: var.hsm_connector_id 
- Add some basic validation in the module to error out explicitely when incompatible inputs are passed with hsm_connector_id  :
   - Error if number_of_crypto_units and hsm_connector_id  are set (as number of cryptor units is set to 3 in that scenario)
   - Error if auto_initialization_using_recovery_crypto_units  and hsm_connector_id  are set
   - ...

**Comment by maheshwarishikha** [comment]
The following features have been added:
- HPCS instance can be created through module and then can be initialized manually.
- HPCS instance creation and initialization through crypto units using this terraform module
- Hybrid HPCS (bring your own HSM): creation and initialization through module
- Existing repos  https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-key-ring and https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-key have been modified for key management of HPCS. It includes update repos to use existing KMS, generalized the repo to use KMS (previously it was KP specific), added new example and tested accordingly.

**Comment by maheshwarishikha** [comment]
All PRs are merged. Hence closing the issue.
