### ISSUE TITLE
Compatibility with TF 0.13

### ISSUE THREAD

**Issue by l2fprod** [terraform-ibm-modules/terraform-ibm-hpcs#3]
The submodules should define a Terraform configuration like the following to be compatible with TF 0.13:

```
terraform {
  required_providers {
    ibm = {
      source = "IBM-Cloud/ibm"
    }
  }
}
```

Right now they fail with:

```
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to install provider

Error while installing hashicorp/ibm: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/ibm
```

See https://www.terraform.io/docs/configuration/modules.html#provider-version-constraints-in-modules

**Comment by kavya498** [comment]
Added..
For now hard-coded it to latest version

**Comment by l2fprod** [comment]
@kavya498 

does this line https://github.com/terraform-ibm-modules/terraform-ibm-hpcs/blob/11197c2f59fc88cbb165b59cc440c3de7896caa0/modules/ibm-hpcs-kms-key/versions.tf#L5 means that you need version 1.20.0 exactly? that sounds a bit restrictive. The provider is already at 1.20.1 this morning https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.20.1
