### ISSUE TITLE
Why the provision_instance var?

### ISSUE THREAD

**Issue by l2fprod** [terraform-ibm-modules/terraform-ibm-hpcs#4]
Why do we have this parameter?

https://github.com/terraform-ibm-modules/terraform-ibm-hpcs/blob/3fcba1d989349d0df0b1f5885e9f84ac1337f1aa/modules/ibm-hpcs-instance/main.tf#L7

If I want the provisioning to be optional, I can remove the module in my terraform or put the count in my terraform, like this:
```
module "hpcs" {
  count = tobool(var.use_hpcs) ? 1 : 0
  source                 = "github.com/terraform-ibm-modules/terraform-ibm-hpcs//modules/ibm-hpcs-instance"

  provision_instance     = tobool(var.use_hpcs)
  resource_group_id      = data.terraform_remote_state.account_structure.outputs.resource_group.id
  service_name           = "${var.basename}-hpcs"
  region                 = var.region
  plan                   = "standard"
  tags                   = concat(var.tags, ["service"])
  number_of_crypto_units = 2
}
```

Also if you keep provision_instance, the output should be changed to return the instance .0 if provision_instance is set.

**Comment by kavya498** [comment]
It was added to contro provisioning..
It is removed now..
Thanks,
