### ISSUE TITLE
Add the service endpoint variable in the hybrid example.

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-hpcs#45]
### Description

Surface https://github.com/terraform-ibm-modules/terraform-ibm-hpcs/blob/main/examples/hybrid-hpcs/variables.tf at https://github.com/terraform-ibm-modules/terraform-ibm-hpcs/blob/735a324c3d2adcc84d5a840145368d921573c256/variables.tf#L104

This will make testing of private end point only simpler.

**Comment by ocofaigh** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-hpcs/pull/47
