### ISSUE TITLE
Missing detailed requirements to use the module

### ISSUE THREAD

**Issue by l2fprod** [terraform-ibm-modules/terraform-ibm-hpcs#5]
- [x] which version of Python do I need?
- [x] on which platforms is the script supported? Linux? macOS? Windows?
- [x] which minimum version of ibmcloud do I need?
- [x] there is no detail on how to install the TKE plugin (`ibmcloud plugin install tke`)

**Comment by kavya498** [comment]
Added.. Please refer 
https://github.com/terraform-ibm-modules/terraform-ibm-hpcs#requirements
https://github.com/terraform-ibm-modules/terraform-ibm-hpcs#pre-requisites-for-initialisation
