### ISSUE TITLE
 A public endpoint is outputted when allowed network is private only.

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-hpcs#55]
Likely an issue with provider / resource controller service - but to investigate further.

A public endpoint is outputted there when allowed network is private only.

2023/07/24 08:15:58 Terraform refresh | Outputs:
2023/07/24 08:15:58 Terraform refresh | 
 2023/07/24 08:15:58 Terraform refresh | hpcs_name = {
2023/07/24 08:15:58 Terraform refresh |   "crn" = "crn:v1:bluemix:public:hs-crypto:eu-fr2:a/06e3c15f0ed94a9aa6682d8277dac7e2:d49ef412-d2b8-493e-a2d9-8a5c442e54ca::"
2023/07/24 08:15:58 Terraform refresh |   "endpoints" = tomap({
2023/07/24 08:15:58 Terraform refresh |     "allowed_network" = "private-only"
2023/07/24 08:15:58 Terraform refresh |     "endpoints.private" = https://api.private.eu-fr2.hs-crypto.cloud.ibm.com:9058/
2023/07/24 08:15:58 Terraform refresh |     "endpoints.public" = https://api.eu-fr2.hs-crypto.cloud.ibm.com:9058/
2023/07/24 08:15:58 Terraform refresh |   })
2023/07/24 08:15:58 Terraform refresh |   "guid" = "d49ef412-d2b8-493e-a2d9-8a5c442e54ca"
2023/07/24 08:15:58 Terraform refresh |   "hpcs_name" = "al4-hpcs"
2023/07/24 08:15:58 Terraform refresh |   "id" = "crn:v1:bluemix:public:hs-crypto:eu-fr2:a/06e3c15f0ed94a9aa6682d8277dac7e2:d49ef412-d2b8-493e-a2d9-8a5c442e54ca::"
2023/07/24 08:15:58 Terraform refresh | }

**Comment by maheshwarishikha** [comment]
It is expected behaviour. You can ignore `public endpoint`. Public endpoint is for reference only if there is a need to enable it temporarily. The behaviour has been documented in Readme.
